name: Java CI

on:
  # Trigger the workflow on push
  # but only for the master branch
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Gradle packages
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean build
    - name: Publish to Artifactory Packages
      run: ./gradlew -PbintrayUser="${bintrayUser}" -PbintrayKey="${bintrayKey}" artifactoryPublish
      env:
        bintrayUser: ${{ secrets.bintrayUser }}
        bintrayKey: ${{ secrets.bintrayKey }}
